@product_id = 995663ef-ba08-49bd-ad93-d6c31700e6e2

###

GET {{baseUrl}}/products
Content-Type: application/json

###

GET {{baseUrl}}/products/{{product_id}}
Content-Type: application/json

###

POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 99
}

###

PUT {{baseUrl}}/products/{{product_id}}
Content-Type: application/json

{
    "price": 99.99
}

###

DELETE {{baseUrl}}/products/{{product_id}}
Content-Type: application/json
