@product_id = 995663ef-ba08-49bd-ad93-d6c31700e6e2

###

GET http://localhost:8000/products
Content-Type: application/json

###

GET http://localhost:8000/products/{{product_id}}
Content-Type: application/json

###

POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 99
}

###

PUT http://localhost:8000/products/{{product_id}}
Content-Type: application/json

{
    "price": 99.99
}

###

DELETE http://localhost:8000/products/{{product_id}}
Content-Type: application/json
